environment:
  nuget_version: '0.11.0-rc1'
  nuget_prerelease: true
  assembly_version: '0.9.0.0'

deploy:
  - provider: GitHub
    description: |
      * Support for .NET Standard 1.3 and NET Core
      * Added support for decimals for ShouldBeCloseTo method (thanks to @meinsiedler)
      * Fixed a bug in ShouldBeLike (#17)
      * We skipped a release number due to an accidentally published 0.10 prerelease package.
    on:
      appveyor_repo_tag: true
    prerelease: $(nuget_prerelease)

    release: v$(nuget_version)
    auth_token:
      secure: VrF5TrpBRN0ims9nJC1LG32O6ga5hsRuGNSufEbatAiIWZ1z68iiCYKZtqnAaT9y

  - provider: NuGet
    api_key:
      secure: R+qirYPrTX9IzJHpRLL6KAV1Lo+vlAnInf6ShiIB2rAGIP28ceJxRAh1jirHE/uD
    on:
      appveyor_repo_tag: true

clone_depth: 5

pull_requests:
  do_not_increment_build_number: true

version: '$(nuget_version)+{build}'
configuration: Release

assembly_info:
  patch: true
  file: Machine.Specifications.Should\Properties\AssemblyInfo.cs
  assembly_version: '$(assembly_version)'

build_script:
  - cmd: >-
      powershell -f build.ps1 -CodeDirectory "." -TestsDirectory "." -PackageOutputDirectory "Build" -Package "Machine.Specifications.Should" -Version "%NUGET_VERSION%" -Configuration "%CONFIGURATION%"
artifacts:
  - path: Build\*.nupkg

test: off