environment:
  nuget_version: '0.10.1-beta1'
  assembly_version: '0.9.3'

pull_requests:
  do_not_increment_build_number: true

clone_depth: 5

version: '$(nuget_version)+{build}'
configuration: Debug

build_script:
- cmd: >-
    powershell -f build.ps1 -AppVeyor -Version "%NUGET_VERSION%" -Configuration %CONFIGURATION%"
artifacts:
- path: Build\*.nupkg

test: off
