environment:
  nuget_version: '0.10.1-beta1'
  nuget_prerelease: true
  assembly_version: '0.10.0.0'

deploy:
  - provider: GitHub
    description: |
      * add lines here

    on:
      appveyor_repo_tag: true
    prerelease: $(nuget_prerelease)

    release: v$(nuget_version)
    auth_token:
      secure: VrF5TrpBRN0ims9nJC1LG32O6ga5hsRuGNSufEbatAiIWZ1z68iiCYKZtqnAaT9y

  - provider: NuGet
    api_key:
      secure: R+qirYPrTX9IzJHpRLL6KAV1Lo+vlAnInf6ShiIB2rAGIP28ceJxRAh1jirHE/uD
    on:
      appveyor_repo_tag: true

pull_requests:
  do_not_increment_build_number: true

clone_depth: 5

version: '$(nuget_version)+{build}'
configuration: Release

assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: '$(assembly_version)'
  assembly_file_version: '$(assembly_version)'
  assembly_informational_version: '$(nuget_version)'

before_build:
  - cmd: >-
      nuget restore

build:
  project: Machine.Specifications.Runner.Console.sln

after_build:
  - cmd: >-
      nuget pack Machine.Specifications.ConsoleRunner\Machine.Specifications.Runner.Console.nuspec -Version %NUGET_VERSION%

test:
  assemblies:
    - Machine.Specifications.ConsoleRunner.Specs.dll

artifacts:
  - path: '*.nupkg'


